# Generated by Django 4.2.2 on 2023-07-02 21:11

from django.db import migrations, models
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('owner', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, verbose_name='user uuid')),
            ],
        ),
    ]
